#!/usr/bin/env python3
"""
LCARS Computer - Initial Setup Script

This script helps configure the LCARS Computer system by:
1. Generating secure random credentials
2. Validating the environment
3. Creating necessary directories
4. Testing connectivity to services

Usage:
    python3 setup.py [--generate-env] [--validate] [--test-services]
"""

import os
import sys
import secrets
import subprocess
import argparse
from pathlib import Path
import platform
import shutil

# ANSI color codes for terminal output
class Colors:
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    CYAN = '\033[96m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'

def print_banner():
    """Print the LCARS-style banner."""
    banner = f"""
{Colors.CYAN}╔══════════════════════════════════════════════════════════════╗
║                                                                ║
║   {Colors.YELLOW}██╗      ██████╗ █████╗ ██████╗ ███████╗{Colors.CYAN}                   ║
║   {Colors.YELLOW}██║     ██╔════╝██╔══██╗██╔══██╗██╔════╝{Colors.CYAN}                   ║
║   {Colors.YELLOW}██║     ██║     ███████║██████╔╝███████╗{Colors.CYAN}                   ║
║   {Colors.YELLOW}██║     ██║     ██╔══██║██╔══██╗╚════██║{Colors.CYAN}                   ║
║   {Colors.YELLOW}███████╗╚██████╗██║  ██║██║  ██║███████║{Colors.CYAN}                   ║
║   {Colors.YELLOW}╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝{Colors.CYAN}                   ║
║                                                                ║
║   {Colors.GREEN}Star Trek Voice Assistant - Setup Utility{Colors.CYAN}                  ║
║                                                                ║
╚══════════════════════════════════════════════════════════════╝{Colors.ENDC}
"""
    print(banner)

def generate_secret(length: int = 32) -> str:
    """Generate a cryptographically secure random hex string."""
    return secrets.token_hex(length)

def generate_password(length: int = 24) -> str:
    """Generate a secure password (base64-like)."""
    return secrets.token_urlsafe(length)

def generate_env_file(env_path: Path, force: bool = False):
    """Generate a secure .env file with random credentials."""
    if env_path.exists() and not force:
        print(f"{Colors.YELLOW}⚠ .env file already exists. Use --force to overwrite.{Colors.ENDC}")
        return False
    
    template_path = env_path.parent / '.env.template'
    
    # Generate secure values
    n8n_encryption_key = generate_secret(32)
    postgres_password = generate_password(24)
    webui_secret_key = generate_secret(32)
    
    env_content = f"""# LCARS Computer - Environment Configuration
# Generated by setup.py - {secrets.token_hex(4)}
#
# SECURITY NOTE: Keep this file secure and never commit to version control.

# ==========================================================================
# GENERAL SETTINGS
# ==========================================================================
TIMEZONE=America/New_York

# ==========================================================================
# N8N CONFIGURATION
# ==========================================================================
N8N_HOST=localhost
WEBHOOK_URL=http://localhost:5678/

# Auto-generated encryption key (DO NOT CHANGE after first run)
N8N_ENCRYPTION_KEY={n8n_encryption_key}

# ==========================================================================
# DATABASE CONFIGURATION
# ==========================================================================
# Auto-generated secure password
POSTGRES_PASSWORD={postgres_password}

# ==========================================================================
# OPEN WEBUI CONFIGURATION
# ==========================================================================
# Auto-generated secret key
WEBUI_SECRET_KEY={webui_secret_key}

# ==========================================================================
# HOME ASSISTANT CONFIGURATION
# ==========================================================================
# TODO: Paste your Long-Lived Access Token from Home Assistant
# Get it from: http://localhost:8123/profile/security
HA_ACCESS_TOKEN=PASTE_YOUR_TOKEN_HERE
HA_URL=http://host.docker.internal:8123

# ==========================================================================
# VOICE PIPELINE SETTINGS
# ==========================================================================
WHISPER_MODEL=medium-int8
PIPER_VOICE=en_US-amy-medium

# Wake word model (openWakeWord / Wyoming)
# Default matches docker-compose.yml. If you add a custom wake word model named
# "computer" into docker/volumes/openwakeword/, set this to "computer".
OPENWAKEWORD_PRELOAD_MODEL=ok_nabu

# ==========================================================================
# GPU CONFIGURATION (uncomment if NVIDIA GPU available)
# ==========================================================================
# NVIDIA_VISIBLE_DEVICES=all
# NVIDIA_DRIVER_CAPABILITIES=compute,utility
"""
    
    with open(env_path, 'w') as f:
        f.write(env_content)
    
    print(f"{Colors.GREEN}✓ Generated secure .env file at: {env_path}{Colors.ENDC}")
    print(f"\n{Colors.YELLOW}IMPORTANT: Edit the .env file and add your Home Assistant token:{Colors.ENDC}")
    print(f"  1. Open Home Assistant: http://localhost:8123")
    print(f"  2. Go to Profile → Security → Long-Lived Access Tokens")
    print(f"  3. Create a new token and paste it into the .env file")
    
    return True

def check_docker():
    """Check if Docker and Docker Compose are available."""
    print(f"\n{Colors.BOLD}Checking Docker installation...{Colors.ENDC}")
    
    try:
        result = subprocess.run(['docker', '--version'], capture_output=True, text=True)
        if result.returncode == 0:
            print(f"{Colors.GREEN}✓ Docker: {result.stdout.strip()}{Colors.ENDC}")
        else:
            print(f"{Colors.RED}✗ Docker not found{Colors.ENDC}")
            return False
    except FileNotFoundError:
        print(f"{Colors.RED}✗ Docker not installed{Colors.ENDC}")
        return False
    
    try:
        result = subprocess.run(['docker', 'compose', 'version'], capture_output=True, text=True)
        if result.returncode == 0:
            print(f"{Colors.GREEN}✓ Docker Compose: {result.stdout.strip()}{Colors.ENDC}")
        else:
            print(f"{Colors.RED}✗ Docker Compose not found{Colors.ENDC}")
            return False
    except FileNotFoundError:
        print(f"{Colors.RED}✗ Docker Compose not installed{Colors.ENDC}")
        return False
    
    return True

def check_nvidia_gpu():
    """Check for NVIDIA GPU availability."""
    print(f"\n{Colors.BOLD}Checking GPU availability...{Colors.ENDC}")
    
    try:
        result = subprocess.run(['nvidia-smi', '--query-gpu=name,memory.total', '--format=csv,noheader'], 
                              capture_output=True, text=True)
        if result.returncode == 0:
            gpus = result.stdout.strip().split('\n')
            for gpu in gpus:
                print(f"{Colors.GREEN}✓ GPU: {gpu}{Colors.ENDC}")
            return True
        else:
            print(f"{Colors.YELLOW}⚠ No NVIDIA GPU detected (CPU inference will be slower){Colors.ENDC}")
            return False
    except FileNotFoundError:
        print(f"{Colors.YELLOW}⚠ nvidia-smi not found (CPU inference will be used){Colors.ENDC}")
        return False

def check_system_resources():
    """Check system RAM and disk space."""
    print(f"\n{Colors.BOLD}Checking system resources...{Colors.ENDC}")

    system = platform.system().lower()

    # Check RAM (best-effort, cross-platform)
    mem_gb = None
    try:
        if system == 'linux' and os.path.exists('/proc/meminfo'):
            with open('/proc/meminfo', 'r') as f:
                for line in f:
                    if line.startswith('MemTotal:'):
                        mem_kb = int(line.split()[1])
                        mem_gb = mem_kb / (1024 * 1024)
                        break
        else:
            # Try psutil if user has it installed (optional)
            try:
                import psutil  # type: ignore
                mem_gb = psutil.virtual_memory().total / (1024 ** 3)
            except Exception:
                mem_gb = None
    except Exception:
        mem_gb = None

    if mem_gb is not None:
        if mem_gb >= 16:
            print(f"{Colors.GREEN}✓ RAM: {mem_gb:.1f} GB (recommended: 16+ GB){Colors.ENDC}")
        else:
            print(f"{Colors.YELLOW}⚠ RAM: {mem_gb:.1f} GB (recommended: 16+ GB){Colors.ENDC}")
    else:
        print(f"{Colors.YELLOW}⚠ Could not determine RAM (install psutil for better detection){Colors.ENDC}")

    # Check disk space (cross-platform)
    try:
        total, used, free = shutil.disk_usage('.')
        free_gb = free / (1024 ** 3)
        print(f"{Colors.GREEN}✓ Available disk space: {free_gb:.1f} GB{Colors.ENDC}")
    except Exception:
        print(f"{Colors.YELLOW}⚠ Could not determine disk space{Colors.ENDC}")

def create_directories(base_path: Path):
    """Create necessary directory structure."""
    print(f"\n{Colors.BOLD}Creating directory structure...{Colors.ENDC}")
    
    dirs = [
        'docker/volumes',
        'homeassistant/config/packages',
        'homeassistant/config/themes',
        'homeassistant/config/sounds',
        'homeassistant/custom_components',
        'docs',
    ]
    
    for dir_path in dirs:
        full_path = base_path / dir_path
        full_path.mkdir(parents=True, exist_ok=True)
        gitkeep = full_path / '.gitkeep'
        if not any(full_path.iterdir()):
            gitkeep.touch()
        print(f"{Colors.GREEN}✓ {dir_path}{Colors.ENDC}")

def test_services():
    """Test connectivity to running services."""
    print(f"\n{Colors.BOLD}Testing service connectivity...{Colors.ENDC}")
    
    import urllib.request
    import urllib.error
    
    services = [
        ('Home Assistant', 'http://localhost:8123/api/', 8123),
        ('n8n', 'http://localhost:5678/healthz', 5678),
        ('Open WebUI', 'http://localhost:3000/', 3000),
        ('Ollama', 'http://localhost:11434/api/tags', 11434),
        ('Whisper', 'http://localhost:10300/', 10300),
        ('Piper', 'http://localhost:10200/', 10200),
    ]
    
    for name, url, port in services:
        try:
            req = urllib.request.Request(url, method='GET')
            with urllib.request.urlopen(req, timeout=5) as response:
                if response.status == 200:
                    print(f"{Colors.GREEN}✓ {name} (port {port}): Online{Colors.ENDC}")
                else:
                    print(f"{Colors.YELLOW}⚠ {name} (port {port}): Status {response.status}{Colors.ENDC}")
        except urllib.error.URLError as e:
            print(f"{Colors.RED}✗ {name} (port {port}): Offline - {e.reason}{Colors.ENDC}")
        except Exception as e:
            print(f"{Colors.RED}✗ {name} (port {port}): Error - {e}{Colors.ENDC}")

def main():
    parser = argparse.ArgumentParser(description='LCARS Computer Setup Utility')
    parser.add_argument('--generate-env', action='store_true', 
                       help='Generate .env file with secure credentials')
    parser.add_argument('--validate', action='store_true',
                       help='Validate system requirements')
    parser.add_argument('--test-services', action='store_true',
                       help='Test connectivity to all services')
    parser.add_argument('--force', action='store_true',
                       help='Force overwrite existing files')
    parser.add_argument('--all', action='store_true',
                       help='Run all setup steps')
    
    args = parser.parse_args()
    
    # If no args, show help
    if len(sys.argv) == 1:
        args.all = True
    
    print_banner()
    
    # Determine base path
    script_path = Path(__file__).resolve()
    base_path = script_path.parent.parent
    docker_path = base_path / 'docker'
    env_path = docker_path / '.env'
    
    print(f"{Colors.CYAN}Project root: {base_path}{Colors.ENDC}")
    
    if args.all or args.validate:
        check_docker()
        check_nvidia_gpu()
        check_system_resources()
        create_directories(base_path)
    
    if args.all or args.generate_env:
        generate_env_file(env_path, args.force)
    
    if args.test_services:
        test_services()
    
    print(f"\n{Colors.CYAN}{'═' * 60}{Colors.ENDC}")
    print(f"{Colors.GREEN}Setup complete! Next steps:{Colors.ENDC}")
    print(f"  1. Edit {docker_path}/.env with your Home Assistant token")
    print(f"  2. cd {docker_path}")
    print(f"  3. docker compose up -d")
    print(f"  4. Access services:")
    print(f"     - Home Assistant: http://localhost:8123")
    print(f"     - n8n: http://localhost:5678")
    print(f"     - Open WebUI: http://localhost:3000")
    print(f"\n{Colors.YELLOW}Live long and prosper. 🖖{Colors.ENDC}\n")

if __name__ == '__main__':
    main()
